### ISSUE TITLE
Is there a way to use the schema in management commands?

### ISSUE THREAD

**Issue by fellipeh** [bernardopires/django-tenant-schemas#223]
Hi, I try to create a management command (https://docs.djangoproject.com/en/1.7/howto/custom-management-commands/), but after a create my tenant, I try to create one record in my tenant model, and error occurred:

django.db.utils.ProgrammingError: relation "core_configempresa" does not exist
LINE 1: INSERT INTO "core_configempresa" ("domain_url", "schema_name...

It seems  in the management command, the schema isn't set correctly...

There's any way to do these?

Regards,

**Comment by fellipeh** [comment]
I try to use this:

```python
tenant = self.get_tenant_from_options_or_interactive(schema_name=schema_name)
connection.set_tenant(tenant)
```

But, new error showed:

"Current schema is %s." % connection.schema_name)
Exception: Can't create tenant outside the public schema. Current schema is localhost.

**Comment by fellipeh** [comment]
What I'm trying to do is:

Create a new tenant, after that, create some record in some models.. here is my full script: https://gist.github.com/fellipeh/4e85922ff7fb14c1b7b8

**Comment by bernardopires** [comment]
Once `novo_cliente.save()` is called, can you see the tables being created on your output? By the way you can simply do `connection.set_tenant(novo_cliente, include_public=False)` instead of `connection.set_tenant(tenant, include_public=False)`

**Comment by fellipeh** [comment]
In fac, I trying to create a Super User, to use the Admin interface, in a public area. In this Admin, I want to create the Client (Tenant).. I try to do these in management command, without Admin interface.. now a realize the correct is using the Admin..

But even in these way, some error showed.. here my history:

- Create a model with custom user
- Put these model in Shared_Apps and Tenant_Apps, because each tenant must have super-user too.
- Create normally all tables.
- When I try to run: ./manage.py createsuperuser
Error:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 55, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 160, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/Users/fellipeh/Developer/django/erpbr/core/models.py", line 68, in create_superuser
    **extra_fields)
  File "/Users/fellipeh/Developer/django/erpbr/core/models.py", line 59, in _create_user
    config.save()
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/tenant_schemas/models.py", line 52, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/tenant_schemas/models.py", line 85, in create_schema
    _check_schema_name(self.schema_name)
  File "/Users/fellipeh/.virtualenvs/erpbr/lib/python3.4/site-packages/tenant_schemas/postgresql_backend/base.py", line 37, in _check_schema_name
    raise ValidationError("Invalid string used for the schema name.")
django.core.exceptions.ValidationError: ['Invalid string used for the schema name.']
```

How can I fix these?

**Comment by bernardopires** [comment]
Seems like you used an invalid string for the schema name. What's the name of the schema?

**Comment by fellipeh** [comment]
Here is the problem...

I wasn't create a schema.. I try to create a super-user in public... and, after create the tenant (and schema)

I try to use: ./manage.py createsuperuser --schema=public

but, informs the --schema is not recognized..

**Comment by bernardopires** [comment]
I can't reproduce your issue.

**Comment by fellipeh** [comment]
:(

I'm really upset... my bad!!! I forgot that in my  "save" on custom user, I try to create the config record ... and these config is now separated in tenant..

Really sorry...
