### ISSUE TITLE
AttributeError: type object 'TestCase' has no attribute 'sync_shared'

### ISSUE THREAD

**Issue by m4l** [bernardopires/django-tenant-schemas#227]
I'm getting this error when running tests with 1.5.1 on Django 1.6, I'm using django-nose as test runner but shouldn't make a difference I reckon:

My dummy test classes:

	class BaseAPITest(TenantTestCase):
		def setUp(self):
			super(BaseAPITest, self).setUp()
			self.client = TenantClient(self.tenant)

	class APITestCases(BaseAPITest):
		def test_user_list(self):
			pass

The traceback

    Traceback (most recent call last):
    File "/home/dev/envs/py26/lib/python2.6/site-packages/nose/suite.py", line 208, in run
      self.setUp()
    File "/home/dev/envs/py26/lib/python2.6/site-packages/nose/suite.py", line 291, in setUp
      self.setupContext(ancestor)
    File "/home/dev/envs/py26/lib/python2.6/site-packages/nose/suite.py", line 314, in setupContext
      try_run(context, names)
    File "/home/dev/envs/py26/lib/python2.6/site-packages/nose/util.py", line 470, in try_run
      return func()
    File "/home/dev/envs/py26/lib/python2.6/site-packages/tenant_schemas/test/cases.py", line 9, in setUpClass
      cls.sync_shared()
    AttributeError: type object 'APITestCases' has no attribute 'sync_shared'

**Comment by bernardopires** [comment]
Should be fixed now, let me know how it goes!

**Comment by m4l** [comment]
Thank you, confirmed working!
