### ISSUE TITLE
AttributeError: FakeTenant instance has no attribute 'domain_url'

### ISSUE THREAD

**Issue by m4l** [bernardopires/django-tenant-schemas#228]
I get this error while running my test cases:

	Traceback (most recent call last):
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/core/handlers/base.py", line 150, in get_response
		response = callback(request, **param_dict)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
		response = view_func(request, *args, **kwargs)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/views/defaults.py", line 23, in page_not_found
		template = loader.get_template(template_name)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/template/loader.py", line 138, in get_template
		template, origin = find_template(template_name)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/template/loader.py", line 127, in find_template
		source, display_name = loader(name, dirs)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/template/loader.py", line 43, in __call__
		return self.load_template(template_name, template_dirs)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/django/template/loader.py", line 46, in load_template
		source, display_name = self.load_template_source(template_name, template_dirs)
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/tenant_schemas/template_loaders.py", line 113, in load_template_source
		for filepath in self.get_template_sources(template_name, template_dirs):
	  File "/home/dev/envs/py26/lib/python2.6/site-packages/tenant_schemas/template_loaders.py", line 101, in get_template_sources
		yield safe_join(template_dir, connection.tenant.domain_url, template_name)
	AttributeError: FakeTenant instance has no attribute 'domain_url'

I can prepare a pull request to add it to the class but I'm not sure what would be the right value for the current use cases in set_schema and set_schema_to_public.

**Comment by bernardopires** [comment]
I can't reproduce. How are you running the tests?

**Comment by m4l** [comment]
The test case throwing an exception made use of django-restframework's APIClient. After swapping the inheritance order in my mixin class it no longer occurred. Maybe this helps someone else:

	class APITenantClient(TenantClient, APIClient):
		def __init__(self, tenant, **defaults):
			super(APITenantClient, self).__init__(tenant=tenant, defaults=defaults)

**Comment by bernardopires** [comment]
This may be my fault because of `TenantClient` not invoking `super` properly.
