### ISSUE TITLE
Error using PostGIS as ORIGINAL_BACKEND

### ISSUE THREAD

**Issue by tecnosegugio** [bernardopires/django-tenant-schemas#240]
I want to use PostGIS with django-tenant-schemas so I set
ORIGINAL_BACKEND = 'django.contrib.gis.db.backends.postgis'
in settings.py but I get an error everytime i run manage.py:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tecnosegugio/Sviluppo/workspaces/tenants/tenants/src/customers/models.py", line 8, in <module>
    from tenant_schemas.models import TenantMixin
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/tenant_schemas/models.py", line 6, in <module>
    from tenant_schemas.postgresql_backend.base import _check_schema_name
  File "/home/tecnosegugio/.virtualenvs/tenants/local/lib/python2.7/site-packages/tenant_schemas/postgresql_backend/base.py", line 147, in <module>
    DatabaseError = original_backend.DatabaseError
AttributeError: 'module' object has no attribute 'DatabaseError'
```

**Comment by tecnosegugio** [comment]
Ok, I've found a way to use PostGIS with tenant-schemas.

**Fast How to:**
* in <yourproject>.settings.py add the lines:
```
ORIGINAL_BACKEND = 'django.contrib.gis.db.backends.postgis'
POSTGIS_VERSION = (2, 1, 4)   # for example (see later)
```
* change postgresql_backend/base.py, lines 147 and 148 with:
```
DatabaseError = django.db.utils.DatabaseError
IntegrityError = psycopg2.IntegrityError
```

**Further details:**
Django-tenant-schemas use settings.ORIGINAL_BACKEND to set which backend we want to 
extend and add schema management. (see at beginning of postgresql_backend/base.py)

Simply using 'django.contrib.gis.db.backends.postgis' as ORIGINAL_BACKEND is not enough because PostGIS backend doesn't expose DatabaseError and IntegrityError exceptions.
Editing base.py let us overcome to this error.

But is not enough: PostGIS DatabaseWrapper init() need a temporary_connection 
to the database to get the PostGIS version directly from the database. 
But at __init__ time the schema management is not ready so we get the error:
```
  File "....../postgresql_backend/base.py", line 129, in _cursor
    if not self.schema_name:
AttributeError: 'DatabaseWrapper' object has no attribute 'schema_name'
```

PostGIS temporary_connection could be avoided if we give it set settings.POSTGIS_VERSION tuple by hand. The POSTGIS_VERSION can be obtained with a simple query in your database:
```
# SELECT postgis_lib_version();
```
Remember to keep up to date this setting if you upgrade your PostGIS in your 
database.

**Comment by gustavoandrescabral** [comment]
Thank you tecnosegugio!
This solution save my day.

**Comment by george-silva** [comment]
saved mine as well.

I'm making a simple PR to address this. Perhaps we can discuss what is the best way to handle this. I just used an simpĺe if.

**Comment by tomturner** [comment]
Can you as make a pull request for the 1.8 version as you will find this version isn't being updated

https://github.com/tomturner/django-tenants

I will make sure it goes in

**Comment by bernardopires** [comment]
Patches are welcome!
