### ISSUE TITLE
Error upgrading to 1.5.2

### ISSUE THREAD

**Issue by quietlyconfident** [bernardopires/django-tenant-schemas#247]
I've been using the @owais branch for Django 1.7 support, and just noticed that DTS now supports it, so I'm trying to switch back to the main branch.

When I switch, I get an error that the Models aren't loaded yet.  If I switch back, the error goes away.  Any clue what might be happening?

````
$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "~/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "~/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "~/.virtualenv/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "~/.virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "~/.virtualenv/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "~/.virtualenv/lib/python2.7/site-packages/tenant_schemas/__init__.py", line 41, in <module>
    get_tenant_model().objects.all().values_list('schema_name', flat=True))
  File "~/.virtualenv/lib/python2.7/site-packages/tenant_schemas/utils.py", line 35, in get_tenant_model
    return get_model(*settings.TENANT_MODEL.split("."))
  File "~/.virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "~/.virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
````

**Comment by quietlyconfident** [comment]
This was not an issue with 1.5.2; it was an issue with PG_EXTRA_SEARCH_PATHS

**Comment by geislor** [comment]
+1

**Comment by davidmir** [comment]
+1

**Comment by davidmir** [comment]
I think I found the problem. On Django >= 1.7 the get_model() function is only available at runtime.

https://docs.djangoproject.com/en/dev/ref/applications/#troubleshooting

**Comment by davidmir** [comment]
Hi,

I'm trying to solve this issue, but so far without success (maybe someone can help :)). 
According to the Django documentation, from version 1.7 to execute code when the Django is already fully loaded we must use the AppConfig (https://docs.djangoproject.com/en/dev/ref/applications/#django.apps.AppConfig.ready).

I did an implementation (https://github.com/sentilant/django-tenant-schemas/tree/fix_app_registry/tenant_schemas) that only perform the verification of PG_EXTRA_SEARCH_PATHS when the AppConfig says that Django is ready. However, never executes the ready() function on AppConfig class and I can not understand why.

**Comment by goodtune** [comment]
This project no longer attempts to support Django versions before 1.8, so I'm closing this as wontfix.
