### ISSUE TITLE
Cannot run the tests

### ISSUE THREAD

**Issue by Hachikooking** [bernardopires/django-tenant-schemas#265]
Hi,

I tried to run the tests using ./manage.py test tenant_schemas.tests as mentionned in the documentation and it gives me an AttributeError: 'module' has no attribute 'tests' while trying to load the tests from their name.

Here is the traceback:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python3.4/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/lib/python3.4/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.4/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python3.4/site-packages/django/test/runner.py", line 144, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/usr/lib/python3.4/site-packages/django/test/runner.py", line 63, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "/usr/lib64/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'tests'
```

**Comment by bernardopires** [comment]
From which folder are you trying to run the tests and which django version are you on? It works for me on django 1.6, 1.7 and 1.8. I'm on python 2.7 though.

**Comment by Hachikooking** [comment]
I ran them from the dts_test_project folder as it's told in the documentation and I used django 1.7

**Comment by bernardopires** [comment]
Can you try with python2? Thanks!

**Comment by Hachikooking** [comment]
I don't have the same issue with python2 (at least it seems to find the tests) but I have the following one. Am I missing something?

```
(env-2.7)[vagrant@fedora dts_test_project]$ ./manage.py test tenant_schemas.tests
/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/tenant_schemas/utils.py:4: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/tenant_schemas/postgresql_backend/base.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Creating test database for alias 'default'...
Got an error creating the test database: database "test_dts_test_project" already exists

Type 'yes' if you would like to try deleting the test database 'test_dts_test_project', or 'no' to cancel: yes
Destroying old test database 'default'...
=== Running migrate for schema public
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 34, in handle
    self.run_migrations(self.schema_name, settings.SHARED_APPS)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 61, in run_migrations
    command.execute(*self.args, **defaults)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 70, in handle
    connection = connections[db]
  File "/home/vagrant/Documents/django-tenant-schemas/dts_test_project/env-2.7/lib/python2.7/site-packages/django/db/utils.py", line 234, in __getitem__
    if hasattr(self._connections, alias):
TypeError: hasattr(): attribute name must be string
```

**Comment by bernardopires** [comment]
That's because this app didn't support Django 1.8 but it does now (since yesterday). Make sure you have the latest version of django-tenant-schemas. Thanks!

**Comment by dozie** [comment]
@bernardopires I am having the same problem from trying to run the tests with django-tenant-schemas 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python34\lib\site-packages\django\core\management\commands\test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Python34\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python34\lib\site-packages\django\core\management\commands\test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "C:\Python34\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\Python34\lib\site-packages\django\core\management\commands\test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Python34\lib\site-packages\django\test\runner.py", line 531, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Python34\lib\site-packages\django\test\runner.py", line 422, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "C:\Python34\lib\unittest\loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'tests'


```

**Comment by bernardopires** [comment]
Try running it on python 2

**Comment by dozie** [comment]
I just noticed if I run the app with python manage.py test tenant_schemas.test
**test** instead of tests works with python 3 though I am not sure if it is the right behavior because I am unable to locate my tenant app schema nor the tables associated with the tenant app. I don't know if that is normal. I haven't gotten around to testing with python 2 yet though.

**Comment by bernardopires** [comment]
Running tests automatically deletes the database at the end

**Comment by dozie** [comment]
@bernardopires  Yeah I forgot to mention I use the keepdb option
