### ISSUE TITLE
optparse.OptionConflictError: option --database: conflicting option

### ISSUE THREAD

**Issue by goodtune** [bernardopires/django-tenant-schemas#272]
Issue when running `migration_schemas` command since `v1.5.3`.

	$ python manage.py migrate_schemas --shared
	Traceback (most recent call last):
	  File "manage.py", line 10, in <module>
	    execute_from_command_line(sys.argv)
	  File "/Users/gary/.virtualenvs/multitenant/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
	    utility.execute()
	  File "/Users/gary/.virtualenvs/multitenant/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
	    self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/Users/gary/Projects/django-tenant-schemas/tenant_schemas/management/commands/migrate_schemas.py", line 24, in run_from_argv
	    super(MigrateSchemasCommand, self).run_from_argv(argv)
	  File "/Users/gary/.virtualenvs/multitenant/lib/python2.7/site-packages/django/core/management/base.py", line 284, in run_from_argv
	    parser = self.create_parser(argv[0], argv[1])
	  File "/Users/gary/.virtualenvs/multitenant/lib/python2.7/site-packages/django/core/management/base.py", line 265, in create_parser
	    option_list=self.option_list)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1219, in __init__
	    add_help=add_help_option)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1261, in _populate_option_list
	    self.add_options(option_list)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1039, in add_options
	    self.add_option(option)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1020, in add_option
	    self._check_conflict(option)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 995, in _check_conflict
	    option)
	optparse.OptionConflictError: option --database: conflicting option string(s): --database

Introduced in commit dee48dc.

**Comment by bernardopires** [comment]
Should be fixed now.
