### ISSUE TITLE
Issues with fake migration on django 1.8

### ISSUE THREAD

**Issue by vinitkumar** [bernardopires/django-tenant-schemas#275]
Here is the stack trace. 

```python
=== Running migrate for schema public
Operations to perform:
  Synchronize unmigrated apps: customers, socialschools_cms, staticfiles, messages, tenant_schemas, djangocms_admin_style, sitemaps, compressor, sekizai, inline_ordering, treebeard, thumbnail
  Apply all migrations: redirects, cmsplugin_logo, sites, cmsplugin_question, cmsplugin_contactbanner, cmsplugin_socialschools, cmsplugin_fourpillars, djangocms_file, cmsplugin_carouseltext, cmsplugin_sociallinks, cmsplugin_gallery, cmsplugin_ga, menus, contenttypes, djangocms_googlemap, sessions, djangocms_column, cmsplugin_login, auth, cmsplugin_googlemaps_multiplemarker, djangocms_picture, djangocms_style, cmsplugin_youtube, cmsplugin_genericbanner, cmsplugin_theme, admin, cms, cmsplugin_twitter, djangocms_link, cmsplugin_linkbanner, cmsplugin_team, djangocms_text_ckeditor
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 35, in handle
    self.run_migrations(self.schema_name, settings.SHARED_APPS)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 53, in run_migrations
    command.execute(*self.args, **self.options)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/vinitkumar/.virtualenvs/cms3/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists
```
I thought of faking it using this command. 

```python
Usage: manage.py migrate_schemas [options]
Updates database schema. Manages both apps with migrations and those without.
manage.py: error: no such option: --fake
```

and this: 

```python
 python manage.py migrate_schemas django_content_type 0001 --fake-initial
Usage: manage.py migrate_schemas [options]
Updates database schema. Manages both apps with migrations and those without.
manage.py: error: no such option: --fake-initial
```
Now, how do I fake a migration here. I am using Django 1.8.3. Please help!

**Comment by kajarenc** [comment]
+1

**Comment by honur** [comment]
Made a pull request #278 that solves this issue
