### ISSUE TITLE
KeyError: u'interactive' when perfoming createsuperuser 

### ISSUE THREAD

**Issue by ronsuez** [bernardopires/django-tenant-schemas#277]
Hello , I'm trying to create a superuser for my tenants , but after I choose the schema it trows me this error: 

Enter Tenant Schema ('?' to list schemas): ?
public - lims.com
lcc_lims - lcc.lims.com
Enter Tenant Schema ('?' to list schemas): lcc_lims
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/tenant_schemas/management/commands/__init__.py", line 128, in handle
    self.command_instance.execute(*args, **options)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/ronsuez/.virtualenvs/lims-core/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 61, in handle
    if not options['interactive']:
KeyError: u'interactive'

**Comment by bernardopires** [comment]
What django version are you on?

**Comment by ronsuez** [comment]
I'm on Django (1.8.4)

**Comment by ronsuez** [comment]
I'm on Django (1.8.4)

**Comment by ezegolub** [comment]
+1 have the same problem

**Comment by jscott1989** [comment]
+1 on 1.8.2

**Comment by fproldan** [comment]
+1

**Comment by bernardopires** [comment]
There was a fix sent a few days ago. Can you guys try updating to the latest version? Thanks!

How are you guys trying to create a superuser? I just tried ``./manage.py tenant_command createsuperuser`` and it worked fine on Django==1.8.4 and 1.7.1.

**Comment by fproldan** [comment]
it's works!
Thanks
