### ISSUE TITLE
custom user model causes NoMigration exception

### ISSUE THREAD

**Issue by wzrd-clss** [bernardopires/django-tenant-schemas#293]
I am trying to share a custom user model. the exception below is thrown when a tenant is being migrated after running tenant.save() . based on the traceback Im guessing that this is due to another app's migration(s) depending on the custom user model which does not exist in the tenant's schema
```
=== Running migrate for schema: dart
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\models.py", line 52, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\models.py", line 116, in create_schema
    verbosity=verbosity)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 20, in handle
    self.migrate_tenant_apps(self.schema_name)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 69, in migrate_tenant_apps
    self._migrate_schema(tenant)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 57, in _migrate_schema
    MigrateCommand().execute(*self.args, **self.options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\management\commands\migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 240, in calculate_dependencies
    migration.calculate_dependencies()
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 374, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 356, in _get_dependency_objects
    migrations = Migrations(app)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 90, in __init__
    self.set_application(application, force_creation, verbose_creation)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 170, in set_application
    raise exceptions.NoMigrations(application)
NoMigrations: Application '<module 'apps.customer' from 'C:\Users\admin\Downloads\git\mango\apps\customer\__init__.pyc'>' has no migrations.
```

I also tried to set TENANT_CREATION_FAKES_MIGRATIONS to False which lead to another exception

```
=== Running migrate for schema: dart
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\models.py", line 52, in save
    self.create_schema(check_if_exists=True, verbosity=verbosity)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\models.py", line 116, in create_schema
    verbosity=verbosity)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 20, in handle
    self.migrate_tenant_apps(self.schema_name)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 68, in migrate_tenant_apps
    self._migrate_schema(tenant)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\tenant_schemas\management\commands\legacy\migrate_schemas.py", line 56, in _migrate_schema
    MigrateCommand().execute(*self.args, **self.options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\core\management\base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\management\commands\migrate.py", line 87, in handle
    apps = list(migration.all_migrations())
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 33, in all_migrations
    yield Migrations(app)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 90, in __init__
    self.set_application(application, force_creation, verbose_creation)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 172, in set_application
    self._load_migrations_module(application.south_migrations)
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 181, in _load_migrations_module
    dirname = self.migrations_dir()
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\south\migration\base.py", line 120, in migrations_dir
    parent = importlib.import_module(".".join(module_path.split(".")[:-1]))
  File "C:\Users\admin\Downloads\git\vmango\lib\site-packages\django\utils\importlib.py", line 41, in import_module
    __import__(name)
ValueError: Empty module name
```

**Comment by tomturner** [comment]
For someone to fix this you should state the version of Django you are using

**Comment by wzrd-clss** [comment]
django 1.6. the custom user model is set up like the one below

AUTH_USER_MODEL = "app.User"

```python
class AbstractUser(auth_models.AbstractBaseUser,
                   auth_models.PermissionsMixin):

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        abstract = True

class CustomUser(AbstractUser):
    pass
```

**Comment by wzrd-clss** [comment]
i got around this issue by moving the custom user model to another app that did not depend on pre-existing migrations

http://stackoverflow.com/questions/14904046/migrating-existing-auth-user-data-to-new-django-1-5-custom-user-model
