### ISSUE TITLE
Erro when apply migrate_schemas with custom user

### ISSUE THREAD

**Issue by fellipeh** [bernardopires/django-tenant-schemas#324]
I have one custom user, and these error show me when I try to run migrate_schemas:

webconflexuser - is my custom user...

I need to have a user control for each tenant... so, I put my model in TENANT_APPS... as showed above:

```
SHARED_APPS = (
    'tenant_schemas',
    'publico',

    'django.contrib.contenttypes',

    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django.contrib.admin',


)

TENANT_APPS = (
    # The following Django contrib apps must be in TENANT_APPS
    'django.contrib.contenttypes',

    'rest_framework',
    'django_filters',
    'bootstrap3',
    'ckeditor',

    'accounts',
    'core',
    'pointlib',
    'cadastro'
)
```

I don't have any model, with FK  to my custom user in my `publico` models.. only my Tenant model, with some Char...

Here is my error:

```
/manage.py migrate_schemas
=== Running migrate for schema public
Operations to perform:
  Apply all migrations: contenttypes, pointlib, sites, auth, publico, sessions, cadastro, core, admin, accounts
Running migrations:
  Rendering model states... DONE
  Applying admin.0001_initial...Traceback (most recent call last):
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "accounts_webconflexuser" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 40, in handle
    self.run_migrations(self.schema_name, settings.SHARED_APPS)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 58, in run_migrations
    command.execute(*self.args, **self.options)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "accounts_webconflexuser" does not exist
```

**Comment by regolith** [comment]
from "`Applying admin.0001_initial...Traceback`" you can see it is the `admin` app that is trying to reference your user model. Try moving `django.contrib.auth` and `django.contrib.admin` to your `TENANT_APPS`. (I do not have a custom user model, but that is where I have those apps)

**Comment by fellipeh** [comment]
Works, moving to TENANT_APPS... but, now.. when I try to add some record in Admin, show me these error:

I think, that's because I don't have any user in my "public".. only in my tenant.. and admin log try to reach out the public schema... just a thought...

```
IntegrityError at /admin/cadastro/mercadoria/add/

insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_accounts_webconflexuser_id"
DETAIL:  Key (user_id)=(1) is not present in table "accounts_webconflexuser".
```

```
Environment:


Request Method: POST
Request URL: http://local.webconflex.com.br:8000/admin/cadastro/mercadoria/add/

Django Version: 1.9.2
Python Version: 3.5.1
Installed Applications:
['tenant_schemas',
 'publico',
 'django.contrib.contenttypes',
 'django.contrib.auth',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.admin',
 'accounts',
 'rest_framework',
 'django_filters',
 'bootstrap3',
 'ckeditor',
 'core',
 'pointlib',
 'cadastro',
 'movimento']
Installed Middleware:
['webconflex.middleware.TenantMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/base.py" in _commit
  211.                 return self.connection.commit()

The above exception (insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_accounts_webconflexuser_id"
DETAIL:  Key (user_id)=(1) is not present in table "accounts_webconflexuser".
) was the direct cause of the following exception:

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/contrib/admin/options.py" in wrapper
  541.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner
  244.             return view(request, *args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/contrib/admin/options.py" in add_view
  1437.         return self.changeform_view(request, None, form_url, extra_context)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/transaction.py" in __exit__
  223.                         connection.commit()

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/base.py" in commit
  242.         self._commit()

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/base.py" in _commit
  211.                 return self.connection.commit()

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/utils.py" in __exit__
  95.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/utils/six.py" in reraise
  685.             raise value.with_traceback(tb)

File "/Users/fellipeh/.virtualenvs/webconflex/lib/python3.5/site-packages/django/db/backends/base/base.py" in _commit
  211.                 return self.connection.commit()

Exception Type: IntegrityError at /admin/cadastro/mercadoria/add/
Exception Value: insert or update on table "django_admin_log" violates foreign key constraint "django_admin_log_user_id_c564eba6_fk_accounts_webconflexuser_id"
DETAIL:  Key (user_id)=(1) is not present in table "accounts_webconflexuser".


```

**Comment by regolith** [comment]
"django_admin_log" and "accounts_webconflexuser" should not exist in the "public" schema, since those apps are not in SHARED_APPS. The admin app will *only* work if you are using it in a tenant schema.

The fix for this problem is not obvious to me... The admin adds a log entry using `request.user.pk` as the user_id for the log entry, so that id must exist in "accounts_webconflexuser" for the log entry to be valid. It doesn't seem possible that the id would not exist, since you are logged in as that user. Could the request user actually exist in a different table? You are logged in to a tenant schema and that user is in that schema's "account_webconflexuser" table, correct? And the model you are adding is in the tenant schema also? It seems like it should work...
