### ISSUE TITLE
Confusion around creating the public tenant object

### ISSUE THREAD

**Issue by john2x** [bernardopires/django-tenant-schemas#335]
In the docs, it says the first step should be to create the "public" Tenant with 

```
from customers.models import Client

# create your public tenant
tenant = Client(domain_url='my-domain.com', # don't add your port or www here! on a local server you'll want to use localhost here
                schema_name='public',
                name='Schemas Inc.',
                paid_until='2016-12-05',
                on_trial=False)
tenant.save()
```

On a newly migrated database, this will fail due to the `public` schema being already existing due to the initial `manage.py migrate_schemas` command.

Setting the `auto_create_schema` property to `False` (which the docs also set/keep to `True`) on the tenant model avoids the issue.

Maybe the docs could recommend instead setting `auto_create_schema` to `False` (and a new method to safely create the schema manually to be added)?

Or maybe the `save` method could check if the schema name is 'public' and skip creation?

**Comment by bernardopires** [comment]
Are you sure it fails? I just went through the instructions in the tutorial and even though the `public` schema existed the code worked just fine. Looking at the `models.py` file, if the schema already exists it simply does nothing.

**Comment by DanPrado** [comment]
I've done this many times (3 or 4 times just today) and had no issues at all. I don't think the problem is on having already a public schema created. Could you post your logs?

**Comment by john2x** [comment]
I'm using Django 1.9.5 and django-tenant-schemas 1.5.8

Here are my logs (I snipped some project specific apps/logs):

```
(venv) vagrant@vagrant-ubuntu-trusty-64:/var/www/project$ ./manage.py migrate_schemas

System check identified some issues:

WARNINGS:
project.CredentialsModel.id: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
project.FlowModel.id: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
=== Running migrate for schema public
Operations to perform:
  Apply all migrations: account, admin, project, sessions, djcelery, customers, auth, sites, contenttypes, kombu_transport_django, taggit
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  ...
  Applying customers.0001_initial... OK
  Applying customers.0002_customeruser... OK
  ...
  Applying kombu_transport_django.0001_initial... OK
  Applying sessions.0001_initial... OK
```

`customers` is the app that contains the `Tenant` model.

Creating the public `Tenant` object (with `auto_create_schema` set to `True`):

```
(venv) vagrant@vagrant-ubuntu-trusty-64:/var/www/project$ ./manage.py shell
Raven is not configured (logging is disabled). Please see the documentation for more information.
/var/www/project/venv/local/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from customers.models import Tenant
>>> Tenant.objects.create(domain_url='localhost', schema_name='public')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/tenant_schemas/models.py", line 57, in save
    self.delete(force_drop=True)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/tenant_schemas/models.py", line 72, in delete
    cursor.execute('DROP SCHEMA %s CASCADE' % self.schema_name)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
ProgrammingError: must be owner of schema public
```

It attempts to `DROP` the public schema, since it already exists.

**Comment by john2x** [comment]
Removing the `self.delete(force_drop=True)` call in the exception handling revealed the real issue. I had signal handlers listening on `post_schema_sync` doing something which shouldn't happen for the public tenant.

Reviewing that part of the code, would something like this be better?
```
        if is_new and self.auto_create_schema:
            try:
                self.create_schema(check_if_exists=True, verbosity=verbosity)
            except:
                # We failed creating the tenant, delete what we created and
                # re-raise the exception
                self.delete(force_drop=True)
                raise
            else:
                post_schema_sync.send(sender=TenantMixin, tenant=self)
```

**Comment by bernardopires** [comment]
I don't understand what difference exactly this would make? As it is right now, if `create_schema` throws an exception it will not run `post_schema_sync`. Your code achieves exactly the same thing?

**Comment by john2x** [comment]
The intent was to only handle exceptions that happened during schema creation (and not mask any exceptions that happen on signal handlers).

**Comment by bernardopires** [comment]
Oh sorry, yes, of course, you're right! Please send a PR with this fix. Thanks!

**Comment by john2x** [comment]
Thanks. Will work on that PR. Closing this.
