### ISSUE TITLE
Strange migration issue with kombu.transport.django

### ISSUE THREAD

**Issue by john2x** [bernardopires/django-tenant-schemas#336]
I'm trying to use [`kombu.transport.django`](https://github.com/celery/kombu/tree/master/kombu/transport/django) as a Celery backend for local development.

My `SHARED_APPS` looks like this:

```
SHARED_APPS = [
    'tenant_schemas',
    'customers',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'raven.contrib.django.raven_compat',
    'oauth2client.contrib.django_util',
    'compressor',
    'djcelery',
    'django_extensions',
    'rest_framework',
    'rest_framework_swagger',
    'allauth',
    'allauth.account',
    'ordered_model',
    'easy_timezones',
    'timezone_field',
    'kombu.transport.django',
]
```

When I run `manage.py migrate_schemas`, it prints out that the migrations got applied:

```
=== Running migrate for schema public
...
Applying kombu_transport_django.0001_initial... OK
...
```

But when I try to use the kombu models, I get a relation does not exist error:

```
>>> from kombu.transport.django.models import Queue
>>> Queue.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/project/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "djkombu_queue" does not exist
LINE 1: ..."djkombu_queue"."id", "djkombu_queue"."name" FROM "djkombu_q...
                                                             ^
```

Doing some introspection shows that the kombu app/models aren't listed:

```
>>> tables = connection.introspection.table_names()
>>> seen_models = connection.introspection.installed_models(tables)
>>> seen_models
set([<class 'djcelery.models.PeriodicTasks'>, <class 'django.contrib.auth.models.Group'>, <class 'djcelery.models.WorkerState'>, <class 'allauth.account.models.EmailAddress'>, <class 'djcelery.models.CrontabSchedule'>, <class 'djcelery.models.PeriodicTask'>, <class 'customers.models.Tenant'>, <class 'django.contrib.auth.models.User'>, <class 'customers.models.CustomerUser'>, <class 'django.contrib.contenttypes.models.ContentType'>, <class 'django.contrib.auth.models.Permission'>, <class 'djcelery.models.TaskMeta'>, <class 'djcelery.models.TaskSetMeta'>, <class 'django.contrib.admin.models.LogEntry'>, <class 'django.contrib.sites.models.Site'>, <class 'django.contrib.sessions.models.Session'>, <class 'allauth.account.models.EmailConfirmation'>, <class 'djcelery.models.TaskState'>, <class 'djcelery.models.IntervalSchedule'>, <class 'customers.models.Customer'>])
>>> tables
[u'account_emailaddress', u'account_emailconfirmation', u'auth_group', u'auth_group_permissions', u'auth_permission', u'auth_user', u'auth_user_groups', u'auth_user_user_permissions', u'celery_taskmeta', u'celery_tasksetmeta', u'customers_customer', u'customers_customeruser', u'customers_tenant', u'django_admin_log', u'django_content_type', u'django_migrations', u'django_session', u'django_site', u'djcelery_crontabschedule', u'djcelery_intervalschedule', u'djcelery_periodictask', u'djcelery_periodictasks', u'djcelery_taskstate', u'djcelery_workerstate']
```

It was working fine prior to using django-tenant-schemas.

**Comment by john2x** [comment]
I created a minimal case here https://github.com/john2x/kombu_tenant_minimal_case

**Comment by john2x** [comment]
It looks the issue occurs for apps that have a custom `app_label` (e.g. it's something other than the default of the last component of the app's `name`). I'll update the minimal case repo.

**Comment by john2x** [comment]
Updated the test repo.

I added two apps, [`nested.app1`](https://github.com/john2x/kombu_tenant_minimal_case/blob/master/nested/app1/apps.py) and [`nested.app2`](https://github.com/john2x/kombu_tenant_minimal_case/blob/master/nested/app2/apps.py). The only difference between the two is that for `nested.app2` I changed the app label to `nested_app2`.

```
> from nested.app1.models import App1
> App1.objects.all()  # ok
[]

> from nested.app2.models import App2
> App2.objects.all()  # can't find the table
...
ProgrammingError: relation "nested_app2_app2" does not exist
LINE 1: ...d_app2_app2"."id", "nested_app2_app2"."name" FROM "nested_ap...
```

**Comment by john2x** [comment]
Adding the following options to the `App2` model doesn't seem to help

```
    class Meta:
        app_label = 'nested_app2'
        db_table = 'nested_app2_app2'
```

**Comment by john2x** [comment]
Oh, and it looks like the tables aren't created at all, despite the migrate command saying OK:

```
                    List of relations
 Schema |            Name            | Type  |   Owner
--------+----------------------------+-------+------------
 public | app1_app1                  | table | collabspot
 public | auth_group                 | table | collabspot
 public | auth_group_permissions     | table | collabspot
 public | auth_permission            | table | collabspot
 public | auth_user                  | table | collabspot
 public | auth_user_groups           | table | collabspot
 public | auth_user_user_permissions | table | collabspot
 public | customers_client           | table | collabspot
 public | django_admin_log           | table | collabspot
 public | django_content_type        | table | collabspot
 public | django_migrations          | table | collabspot
 public | django_session             | table | collabspot
(12 rows)
```

(Sorry for spamming)

**Comment by bernardopires** [comment]
Thanks for looking into this! You've already pinpointed the issue: it's the custom `app_label`. This means our custom router is at fault here. I'm looking for a fix now.

**Comment by bernardopires** [comment]
This should be fixed now. Sorry, this was my bad!

**Comment by faxioman** [comment]
Hi @bernardopires, is this fixed in tenant schema 1.9?
I have the same problem (silent fail with no table created) using in django 1.11 with some app with this configuration:

```
class CatalogConfig(AppConfig):
    name = 'tenant_apps.thecustomer.catalog'
    label = 'thecustomer_catalog'
    verbose_name = _('Catalog')
```

**Comment by faxioman** [comment]
Ok @bernardopires, I see that method app_labels in tenant_schemas.utils is broken.
For an app configured like in my previous comment the app_labels method returns "catalog" as label instead of 'thecustomer_catalog'

**Comment by faxioman** [comment]
This is my temporary horrible workaround:

```
def _app_labels(apps_list):
    from django.conf import settings

    labels = []

    for app in apps_list:
        app_entry = app
        # check if the app is registered through an AppConfig modules
        for iapp in settings.INSTALLED_APPS:
            if iapp.startswith("{}.apps.".format(app)):
                app_entry = iapp
                break

        labels.append(AppConfig.create(app_entry).label)

    return labels
```
