### ISSUE TITLE
Compatibility issue with Django 1.10.1 for createsuperuser command

### ISSUE THREAD

**Issue by nikhiln** [bernardopires/django-tenant-schemas#394]
Getting following error on running `createsuperuser` command.

```
$ python backend/manage.py createsuperuser --username='admin' --schema=test
Traceback (most recent call last):
  File "backend/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nikhil/env/ad2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/nikhil/env/ad2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nikhil/env/ad2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/nikhil/env/ad2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    return module.Command()
  File "/home/nikhil/env/ad2/local/lib/python2.7/site-packages/tenant_schemas/management/commands/__init__.py", line 123, in __new__
    obj.option_list = obj.command_instance.option_list
AttributeError: 'Command' object has no attribute 'option_list'
```

I think you already resolved same issue for `migrate_schemas` sometime ago, can we apply the same solution to fix other tenant wrapped commands?

The solution would be to do change in `TenantWrappedCommand` class in `__new__` method at line 123 in  [management/commands/**init**.py](https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/management/commands/__init__.py)

We can change that line to following:

```
if django.VERSION <= (1,10,0):
        obj.option_list = obj.command_instance.option_list
```

Thoughts?

**Comment by bernardopires** [comment]
Yes, please, would you send a PR fixing this and the other commands? (Might be a better idea to just fix the parent class which I think almost all commands inherit from)

**Comment by nikhiln** [comment]
Closing this in reference to PR #397

**Comment by filipeximenes** [comment]
Do we have a release date for this (in pypi)?

**Comment by yianlai** [comment]
Do we have a release date for this?!
