### ISSUE TITLE
pip install - docker

### ISSUE THREAD

**Issue by jameswinegar** [bernardopires/django-tenant-schemas#434]
Installing django-tenant-schemas on a docker container throws `UnicodeDecodeError`  when parsing `README.rst` for the `long_description`

Base Image: `FROM ubuntu:16.04`
Work around is using `ENV LC_CTYPE C.UTF-8`

Traceback
```
Collecting django-tenant-schemas (from -r /home/docker/code/app/requirements/base.txt (line 8))
  Downloading django-tenant-schemas-1.6.11.tar.gz (52kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a_llv54i/django-tenant-schemas/setup.py", line 29, in <module>
        long_description=open('README.rst').read() if exists("README.rst") else "",
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 436: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a_llv54i/django-tenant-schemas/
```

**Comment by goodtune** [comment]
What is the base image when you encounter this?

**Comment by jameswinegar** [comment]
@goodtune base image was ubuntu:16.04 sorry
