### ISSUE TITLE
Not able to create a new tenant client!

### ISSUE THREAD

**Issue by vivekamin** [bernardopires/django-tenant-schemas#440]
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django_tenants/models.py", line 99, in save
    self.delete(force_drop=True)
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django_tenants/models.py", line 114, in delete
    if schema_exists(self.schema_name) and (self.auto_drop_schema or force_drop):
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django_tenants/utils.py", line 99, in schema_exists
    cursor.execute(sql, (schema_name, ))
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/yodaplus/Documents/env_teamnest/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
``
```

**Comment by vivekamin** [comment]
SOLVED!

**Comment by rajeshbk042** [comment]
Hi @vivekamin ,

I am getting same issue. How did you solved this issue?. Could you please share the detail?

Regards,
Rajesh

**Comment by vivekamin** [comment]
remove migarion files from applications of django. Not every file. just files which has been created after migrate_schemas

**Comment by rajeshbk042** [comment]
Hi @vivekamin ,
I have deleted all migration file that generated the results of `migrate_schemas` command but its not working. My project was configured with Django 1.5.5 with django_tenant_schamas 1.4.5.

Waiting for the valuable thoughts..

Regards,
Rajesh

**Comment by goodtune** [comment]
Please move up to supported version of both Django and django-tenant-schemas, those are both ancient.

**Comment by vivekamin** [comment]
That's true. I am using 1.9
