### ISSUE TITLE
Entry in INSTALLED_APPS but not in SHARED_APPS or TENANT_APPS can't migrate

### ISSUE THREAD

**Issue by goodtune** [bernardopires/django-tenant-schemas#443]
This bit me this morning... I added an application to `INSTALLED_APPS` but forgot to include it in `TENANT_APPS`; when I started migrating the migration code was not being executed, although the migration *was* being marked as processed, and even recorded in the database.

Ultimately though this is an error state - an application that isn't allocated one way or the other can't be migrated because we don't know if it is intended to be in `SHARED_APPS` or `TENANT_APPS`. Guessing or defaulting is worse, so I think the best solution is to add this to the system checks.

**Comment by stephane** [comment]
The installation could recommend to use:

`INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]`

Extracted from http://mycodesmells.com/post/django-tutorial-multi-tenant-setup

**Comment by bernardopires** [comment]
That's interesting, I was about to say the docs already recommend something similar and was surprised to see it doesn't. I completely agree it should @stephane. Please send a pull request for this. Thanks!

**Comment by amitjindal** [comment]
Hi, I am seeing another problem that is a little similar to this.
Please note that my project is a cookiecutter-django so the application directory structure is different.

## Error

```
?: (tenant_schemas.E002) You have TENANT_APPS that are not in INSTALLED_APPS
	HINT: ['myapplication.reporter', 'myapplication.reviewer', 'raven.contrib.django.raven_compat']
?: (tenant_schemas.E003) You have SHARED_APPS that are not in INSTALLED_APPS
	HINT: ['myapplication.tenant_accounts']

System check identified 2 issues (0 silenced).
```

**Here's my inclusion:**
```
INSTALLED_APPS = DJANGO_SHARED_APPS + DJANGO_TENANT_APPS
SHARED_APPS = DJANGO_SHARED_APPS
TENANT_APPS = DJANGO_TENANT_APPS
```


Note that I did a print of these lists in the config and they seem perfectly fine to me:

**INSTALLED_APPS**
Broken into multiple lines for clarity below:
```
['tenant_schemas', 'myapplication.tenant_accounts', 'django.contrib.auth',
'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 
'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.admin', 'crispy_forms',
'allauth', 'allauth.account', 'allauth.socialaccount', 'attachments',
'organizations', 'django_ajax', 'myapplication.users',
'myapplication.core', 'myapplication.reporter', 'myapplication.reviewer',
'compressor', 'raven.contrib.django.raven_compat', 'gunicorn',
'storages', 'anymail']
```

**SHARED_APPS**
```
['tenant_schemas', 'myapplication.tenant_accounts']
```

**TENANT_APPS**
```
['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions',
'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles',
'django.contrib.admin', 'crispy_forms', 'allauth',
'allauth.account', 'allauth.socialaccount', 'attachments', 'organizations',
'django_ajax', 'myapplication.users',
'myapplication.core', 'myapplication.reporter', 'myapplication.reviewer',
'compressor', 'raven.contrib.django.raven_compat', 'gunicorn',
'storages', 'anymail']
```

**What I am seeing is:**
1) If I give name of the config instead of just the application, I get error that application is not in installed apps: e.g.:
```
LOCAL_APPS += ['myapplication.reviewer.apps.ReviewerConfig']
```
2) If I don't give name of the config but just use `default_app_config = 'myapplication.tenant_accounts.apps.TenantAccountsConfig'` in `__init__.py`  then also I get an error.
```
LOCAL_APPS += ['myapplication.reviewer']
```
```
default_app_config = 'myapplication.reviewer.apps.ReviewerConfig'
 -- or --
default_app_config = 'reviewer.apps.ReviewerConfig'
```

3) When I don't give either, this works fine but other things like django shell `manage.py shell` is not able to load the models.
```
LOCAL_APPS += ['myapplication.reviewer']
```

Currently the application (Raven/Third party): `'raven.contrib.django.raven_compat'` is still giving error.
There seems to be a bug with the code that does this system check as its not able to correctly identify the packages. Or perhaps I have missed a setting that sets this up correctly.

How do I work around this? Please help.

**Comment by amitjindal** [comment]
Here's a little more info that I see:

In my config I wrote similar code as: https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/apps.py#L82

The check passes when its running in config, but fails later. Not sure why.

**Settings**
```
print('--------------------------------------------------------------------------------------------')
INSTALLED_APPS = DJANGO_SHARED_APPS + DJANGO_TENANT_APPS
SHARED_APPS = set(DJANGO_SHARED_APPS)
TENANT_APPS = set(DJANGO_TENANT_APPS)

if not set(TENANT_APPS).issubset(INSTALLED_APPS):
    delta = set(TENANT_APPS).difference(INSTALLED_APPS)
    print("AMIT: You have TENANT_APPS that are not in INSTALLED_APPS: %s" % [a for a in TENANT_APPS if a in delta])
else:
    print("AMIT: TENANT_APPS check passed")

if not set(SHARED_APPS).issubset(INSTALLED_APPS):
    delta = set(SHARED_APPS).difference(INSTALLED_APPS)
    print("AMIT: You have SHARED_APPS that are not in INSTALLED_APPS: %s" % [a for a in SHARED_APPS if a in delta])
else:
    print("AMIT: SHARED_APPS check passed")
print('--------------------------------------------------------------------------------------------')
```

**Output (Relevant Output)**
```
System check identified 1 issue (0 silenced).
--------------------------------------------------------------------------------------------
AMIT: TENANT_APPS check passed
AMIT: SHARED_APPS check passed
--------------------------------------------------------------------------------------------
[2017-11-23 12:01:01,130] [  DEBUG] [base] [7122:140184782518016] - Configuring Raven for host: <raven.conf.remote.RemoteConfig object at 0x7f7f45e7c4e0>
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7f45e1c598>
[2017-11-23 12:01:02,608] [  DEBUG] [base] [7122:140184609859328] - Sending message of length 1902 to https://sentry.io/api/234044/store/
Traceback (most recent call last):
  File "/webapps/myapplication/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/webapps/myapplication/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/webapps/myapplication/lib/python3.6/site-packages/django/core/management/base.py", line 405, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (tenant_schemas.E002) You have TENANT_APPS that are not in INSTALLED_APPS
	HINT: ['raven.contrib.django.raven_compat']

System check identified 1 issue (0 silenced).
```

Any reason why this would be?

Thanks
Amit

**Comment by ivissani** [comment]
I'm experiencing the same problem as @amitjindal . As far as I can see the problem is located in the `apps.py` file and is  a consequence of this piece of code

```python
    # Take the app_configs and turn them into *old style* application names.
    # This is what we expect in the SHARED_APPS and TENANT_APPS settings.
    INSTALLED_APPS = [
        config.name
        for config in app_configs
    ]
```

The problem is that `config.name` for  `raven.contrib.django.raven_compat` returns `'raven.contrib.django'` therefore the following test

```python
    if not set(settings.SHARED_APPS).issubset(INSTALLED_APPS):
        delta = set(settings.SHARED_APPS).difference(INSTALLED_APPS)
        errors.append(
            Error("You have SHARED_APPS that are not in INSTALLED_APPS",
                  hint=[a for a in settings.SHARED_APPS if a in delta],
                  id="tenant_schemas.E003"))
```

fails, producing the mentioned error.

Shouldn't this code:

```python
    # Take the app_configs and turn them into *old style* application names.
    # This is what we expect in the SHARED_APPS and TENANT_APPS settings.
    INSTALLED_APPS = [
        config.name
        for config in app_configs
    ]
```

be erased and use `settings.INSTALLED_APPS` instead?

**Comment by cmabastar** [comment]
Hi, 

Any resolution for this issue? I Just upgraded my package to 1.9.0 and now receiving this error for the sentry package.

**Comment by kranirudha** [comment]
Same here. Any resolution ?

**Comment by axelvdw** [comment]
Any resolution for this issue? Having the same problem regarding the raven/sentry package.

**Comment by tobiasgoecke** [comment]
Same here. Any resolution ?

**Comment by cmabastar** [comment]
What i did was just rename the module.

```
# 'raven.contrib.django.raven_compat', latest django-tenant-schemas breaks this module
'raven.contrib.django',
```

**Comment by jlquichimbo** [comment]
I just put a single name app in TENANT_APPS:
`TENANT_APPS = (
    'app',
    'usuarios',
    'productos',
    'ventas',
    'medidas',
    # 'app.apps.AppConfig',
    # 'usuarios.apps.UsuariosConfig',
    # 'productos.apps.ProductosConfig',
    # 'ventas.apps.VentasConfig',
    # 'medidas.apps.MedidasConfig',
)`

And it works for me.
