### ISSUE TITLE
Example Project: relation "customers_client" does not exist

### ISSUE THREAD

**Issue by danielmaddern** [bernardopires/django-tenant-schemas#475]
Cloned the repo, configured the database and ran ./manage.py migrate_schemas
This is the error I get.  

Ubuntu 16.04.02
Python 3.5.2
django 1.11

```python
(django) daniel@daniel-ubuntu:~/Development/django-tenant-schemas/dts_test_project$ ./manage.py migrate_schemas
=== Running migrate for schema public
Operations to perform:
  Apply all migrations: auth, contenttypes, dts_test_app, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "customers_client" does not exist
LINE 1: ...escription", "customers_client"."created_on" FROM "customers...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 51, in handle
    for tenant in all_tenants:
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/daniel/Development/pythons/django/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "customers_client" does not exist
LINE 1: ...escription", "customers_client"."created_on" FROM "customers...
```

**Comment by danielmaddern** [comment]
tried with django 1.10, same issue

**Comment by danielmaddern** [comment]
forgot to migrate customers :(
