### ISSUE TITLE
Getting ImportError when running tenant_schema tests

### ISSUE THREAD

**Issue by nknganda** [bernardopires/django-tenant-schemas#496]
When running `python manage.py test tenant_schemas` getting the following ImportError

`
Creating test database for alias 'default'...
EEEEEEE
`
`
ERROR: tenant_schemas.tests.test_tenants (unittest.loader.ModuleImportFailure)
ImportError: Failed to import test module: tenant_schemas.tests.test_tenants
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/.virtualenvs/ttc/local/lib/python2.7/site-packages/tenant_schemas/tests/__init__.py", line 1, in <module>
    from .template_loader import *
ImportError: No module named template_loader
`

**Comment by Neddz** [comment]
I am getting exactly the same error when I run either `python manage.py test tenant_schemas` or `python manage.py test tenant_schemas.tests`.

```ImportError: Failed to import test module: tenant_schemas.tests
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/tests/__init__.py", line 1, in <module>
    from .template_loader import *
ModuleNotFoundError: No module named 'tenant_schemas.tests.template_loader'
```
OS: Debian GNU/Linux 9 (stretch)
Python: 3.6.1

**Comment by mehemmelbachir** [comment]
@Neddz ... Same error ... any solutions please!

Running `python manage.py test tenant_schemas.tests`
Result:
> `ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "c:\users\mehem\appdata\local\programs\python\python36\Lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "D:\PycharmProjects\plannit2\Backend\ENV\lib\site-packages\tenant_schemas\tests\__init__.py", line 1, in <module>
    from .template_loader import *
ModuleNotFoundError: No module named 'tenant_schemas.tests.template_loader'`

**Comment by goodtune** [comment]
Has anyone tried fixing the import rather than just expecting someone else to fix their problem?

**Comment by FredeJ** [comment]
I just took a look at this, as I'm running into the same error. It seems that the pypi version (1.9) includes `template_loader` in the `tenant_schemas/tests/__init__.py` file but the folder is not present.

A fix would therefore be either:
- Removing the include for the (missing) folder.
- Releasing version 1.9.1(?) which includes the subfolder.

I'm not sure how to go about solving this, but anyone knowledgable about releasing to pypi should probably be able to do it in no time :)
