### ISSUE TITLE
What is the use of collectstatic_schemas?

### ISSUE THREAD

**Issue by durkode** [bernardopires/django-tenant-schemas#500]
I recently had to make a tenant aware admin command, which was extremely easy due to subclassing BaseTenantCommand, the example of which was collectstatic made into collectstatic_schemas. However I can't work out why you would ever need collectstatic_schemas. I tried running it and all it did (as expected) was run collectstatic once for each tenant, each time overwriting the same files. Is there a use case for collectstatic_schemas that I am unaware of?

Note: this is a question, not an issue or bug. Love your work

**Comment by indytraub** [comment]
+1 I had the same observation and question.

**Comment by rishikesh67** [comment]
In my case, I am getting the following issue when I am trying to run the collectstatic_schemas command.

```bash
(venv3.6.7.26apr) ➜  src git:(master) ✗ python manage.py collectstatic_schemas       
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/hygull/Desktop/try_django_tenant_schemas/venv3.6.7.26apr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/hygull/Desktop/try_django_tenant_schemas/venv3.6.7.26apr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/hygull/Desktop/try_django_tenant_schemas/venv3.6.7.26apr/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/hygull/Desktop/try_django_tenant_schemas/venv3.6.7.26apr/lib/python3.6/site-packages/django/core/management/__init__.py", line 37, in load_command_class
    return module.Command()
  File "/Users/hygull/Desktop/try_django_tenant_schemas/venv3.6.7.26apr/lib/python3.6/site-packages/tenant_schemas/management/commands/__init__.py", line 27, in __new__
    app_name = get_commands()[obj.COMMAND_NAME]
KeyError: 'collectstatic'
```

**Comment by jamosoma** [comment]
Someone Solve this? same error here.

**Comment by kareemcoding** [comment]
Did you guys get any further with this?
