### ISSUE TITLE
Custom User Model Support

### ISSUE THREAD

**Issue by devxpy** [bernardopires/django-tenant-schemas#525]
Does  it work with Custom User Models?
Because I am getting this error whenever i try to do the first
`python manage.py migrate_schemas --shared`

```
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "Users_customuser" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 42, in handle
    executor.run_migrations(tenants=[self.schema_name])
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 58, in run_migrations
    run_migrations(self.args, self.options, self.codename, public_schema_name)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/tenant_schemas/migration_executors/base.py", line 31, in run_migrations
    MigrateCommand(stdout=stdout, stderr=stderr).execute(*args, **options)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 117, in execute
    cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vagrant/.pyenv/versions/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "Users_customuser" does not exist


```

(Users is the name of app and CustomUser is the custom user model name)

Here is my settings.py

```
TENANT_MODEL = "Tenants.PaidClient"
SHARED_APPS = (
    'tenant_schemas',
    'Tenants',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'rest_framework',
    'django_extensions',
    'phonenumber_field',
    'multiselectfield',
    'widget_tweaks',

    'Users',
    'Exams',
)

```

Using django 2.0.1 django-tenant-schemas 1.9.0

**Comment by bonzomontreus** [comment]
I am struggling with the same problem, How were you able to solve this?

**Comment by devxpy** [comment]
you need to reset db each time you change the SHARED_APPS. After doing that and running migrate_schemas again, it was fine.

That being said,  I found tenant schemas to be very unpredictable if you want to do any sort of customization.
Thus, I have ditched tenant schemas in favour of groups and a custom domain object.

You do need to do more work, as it doesn't switch the schema automatically and you have to filter objects manually based on the domain

```
class GroupDomain(models.Model):
    EMAIL = 1
    PHONE_NUMBER = 2
    LOGIN_METHODS = ((PHONE_NUMBER, 'Phone Number'),
                     (EMAIL, 'Email'),)

    group = models.OneToOneField(Group, on_delete=models.CASCADE, primary_key=True)

    domain = models.CharField(null=True, max_length=255, unique=True)
    display_name = models.CharField(max_length=255, blank=True, null=True,
                                    help_text=_('Display name for home page. Domain name will be used if left blank'))
    display_image = models.ImageField(blank=True, null=True)
    login_method = models.IntegerField(default=PHONE_NUMBER, choices=LOGIN_METHODS,
                                       help_text=_('Method to use for login'))
```
Here is a middleware that comes in handy
```
class GroupDomainMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        request.group_domain = get_object_or_404(GroupDomain, domain=request.META['HTTP_HOST'])
        response = self.get_response(request)
        return response
```

Let me know if you plan to this.

**Comment by bonzomontreus** [comment]
I didn't know that about the SHARED_APPS, it works now. I need a lot of django-tenant-schemas functionalities so I will keep it but thanks you

**Comment by nevermorever** [comment]
@bonzomontreus hi bro, have you worked out how to support custom user model?

**Comment by devxpy** [comment]
I think I did for sometime, but then it felt `too hacky` to be used in production so I switched to my own implementation. 
What error are you getting?

**Comment by nevermorever** [comment]
@devxpy also the same kind errr with you .

**Comment by devxpy** [comment]
you need to reset db each time you change the SHARED_APPS. After doing that and running migrate_schemas again, it was fine.

try to use the reset_db command from django extensions or manually destroy db from psql

**Comment by nevermorever** [comment]
thanks for your advice，but its not a good choice in production 。

**Comment by bonzomontreus** [comment]
Since I wasnt in production, I was able to reset the db without problems and that fixed the problem

**Comment by devxpy** [comment]
Yes, but the problem is what if you're in production and you realize that you need to make changes.?

**Comment by goodtune** [comment]
Clearly the custom user model feature works, many of us (self included) use it.

If you had or have a misconfiguration then that is something your project needs to rectify, not the open source app that you hitched your wagon to.
