### ISSUE TITLE
problem with middleware

### ISSUE THREAD

**Issue by mezitax** [bernardopires/django-tenant-schemas#590]
Hi guys, I've been trying to make my tenant work without success for a couple of days.
Apparently the problem is in the midddleware configuration.
This is my error:
```
Forbidden (Permission denied): /admin/login/
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\utils\deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "C:\Python36\lib\site-packages\django\middleware\clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'NoneType' object has no attribute 'get'
[29/Jan/2019 18:47:03] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 75281
```
My middleware:
```
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'tenant_schemas.middleware.DefaultTenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',#antes de autenticationmiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
```
the error happens trying to enter the url of the tenant and the public schema
I do not know how to track an error like this, since the terminal does not give me much information.

Could someone give me a hand to go in the right direction please?

**Comment by mezitax** [comment]
I'm sorry, it's my problem
I had a context processors in my shared shema that called a resource that did not exist yet because it is from the tenant shema.
