### ISSUE TITLE
[solved] How to use crontab and django tenants for tasks

### ISSUE THREAD

**Issue by alisonsandrade** [bernardopires/django-tenant-schemas#636]
Good evening. 

I'm trying to use crontab with django_tenants_schemas, but to no avail.
I am using the `Kronos` library (https://github.com/jgorset/django-kronos) and I have done all the configuration. When trying to include the task the command line is added to the Unix crontab, but it does not execute.

When debugging the code I realized that I am suffering from the `django.db.utils.ProgrammingError` error, most likely because crontab is trying to execute the tasks directly from the public schema and in this schema it does not have the task tables.

Can anyone indicate a solution? I know that there is a `django_tenant_celery` library, but as my tasks are quite simple I didn't want to have to use celery.

Thank you very much in advance.

I'm using:
- Django 3
- Python 3.6.9
- django_tenants_schema 1.10
- Linux Mint 19.3
```
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/alison/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/alison/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alison/.local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alison/.local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/alison/Documentos/geproc/venv/lib/python3.6/site-packages/kronos/management/commands/runtask.py", line 20, in handle
    return task.function()
  File "/home/alison/Documentos/geproc/geproc/apps/agenda/cron.py", line 35, in send_mail_lembrete_job
    for tarefa in tarefas:
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alison/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "agenda_tarefa" does not exist
LINE 1: ..."."created_at", "agenda_tarefa"."updated_at" FROM "agenda_ta...
```

**Comment by alisonsandrade** [comment]
After several attempts and debugging I finally got it. I will leave the answer registered here so that someone who has the same problem can be helped.

The problem is that manage.py was executing the crontab command taking into account the public schema and as it does not have all the tables it triggers the `ProgrammingError` error.

The solution was to exclude the public schema from the send_mail function as follows:
```
@kronos.register('* * * * *')
def send_mail_job():
    for tenant in get_tenant_model().objects.all():
        if tenant.schema_name != 'public':
            with tenant_context(tenant):
                [...]
```
