### ISSUE TITLE
After upgrading django 2.0 to 3.0, shell tenant command stop working

### ISSUE THREAD

**Issue by Mario-Cano** [bernardopires/django-tenant-schemas#641]
I moved from django 2.0 to 3.0 and shell tenant command stop working.

I'm doing something like this 

_./manage.py tenant_command shell --schema=customer1,_

I'm getting this error
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mario/anaconda3/envs/myapp/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/anaconda3/envs/myapp/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/anaconda3/envs/myapp/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/anaconda3/envs/myapp/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/user/anaconda3/envs/myapp/lib/python3.6/site-packages/tenant_schemas/management/commands/tenant_command.py", line 15, in handle
    call_command(command, *args, **options)
  File "/home/user/anaconda3/envs/myapp/lib/python3.6/site-packages/django/core/management/__init__.py", line 160, in call_command
    ', '.join(sorted(valid_options)),
TypeError: Unknown option(s) for shell command: skip_checks. Valid options are: command, force_color, help, interface, no_color, no_startup, pythonpath, settings, stderr, stdout, traceback, verbosity, version.

Do you have any suggestion about how to fix it?

**Comment by estebanangelm** [comment]
I have this exact same issue. It was a very cool feature to start the django console with the single line command. Hope you can fix it!

**Comment by sshahbaj** [comment]
Check issue #634

**Comment by goodtune** [comment]
Thank you for reporting this issue. However, we are now focusing all development efforts on supporting only Django LTS versions (4.2+) and Python 3.8+. This issue mentions upgrading from Django 2.0 to Django 3.0, both of which are below our current minimum supported version.

As part of our modernization initiative, we're closing issues that target outdated Django/Python versions to streamline maintenance and focus resources on current technologies.

If this issue still exists with Django 4.2+ and Python 3.8+, please re-open this issue with updated version details rather than creating a new one.

Thank you for your understanding!

**Comment by judemcenerny** [comment]
This is happening with django 5.2.4 and python 3.13.5
I do not have permission to re-open, or I would.

Reproducible with the below.  

```
from django.core.management import call_command
from django.core.management.base import BaseCommand
from io import StringIO
from django.conf import settings


class Command(BaseCommand):
    help = 'Runs all Django tests, or specific tests if specified.   Then sends a status email.'

    def handle(self, *args, **options):
        self.stdout.write("Starting Django tests...")

        test_output = StringIO()

        try:
            call_command('test', stdout=test_output, stderr=test_output, *args, **options)
            self.stdout.write(self.style.SUCCESS('Tests finished.'))
        except SystemExit as e:
            self.stderr.write(self.style.ERROR(f'Tests failed with SystemExit: {e}'))
```

When the outer Command is run, `django/core/management/base.py` function `create_parser()` is adding base arguments, including "--skip-checks" at line 366, to the arguments.  Then this Command's `call_command()` fails with TypeError at `django/core/management/__init__.py` line 179 when 'skip_checks' is found in unknown_options.
