### ISSUE TITLE
ModuleNotFoundError: No module named 'tenant_schemas'

### ISSUE THREAD

**Issue by souzagilson15** [bernardopires/django-tenant-schemas#646]
when trying to run using uwsgi the message is informed: 

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
PEP 405 virtualenv detected: /meuapp/venv
Set PythonHome to /meuapp/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a49f129fb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 801944 bytes (783 KB) for 10 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./portalCliente/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/meuapp/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/meuapp/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/meuapp/venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/meuapp/venv/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ModuleNotFoundError: No module named 'tenant_schemas'**
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 43723)
spawned uWSGI worker 1 (pid: 43725, cores: 1)
spawned uWSGI worker 2 (pid: 43726, cores: 1)
spawned uWSGI worker 3 (pid: 43727, cores: 1)
spawned uWSGI worker 4 (pid: 43728, cores: 1)
spawned uWSGI worker 5 (pid: 43729, cores: 1)
spawned uWSGI worker 6 (pid: 43730, cores: 1)
spawned uWSGI worker 7 (pid: 43731, cores: 1)
spawned uWSGI worker 8 (pid: 43732, cores: 1)
spawned uWSGI worker 9 (pid: 43733, cores: 1)
spawned uWSGI worker 10 (pid: 43734, cores: 1)
^CSIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
worker 9 buried after 1 seconds
worker 10 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /meuapp/portalcliente/portalCliente/mysite.sock removed.
(venv) root@vps21715:/meuapp/portalcliente# pip3 install django-tenant-schemas
****Requirement already satisfied:** django-tenant-schemas in /usr/lib/python3.6/site-packages
Requirement already satisfied: ordered-set in /usr/lib/python3.6/site-packages (from django-tenant-schemas)
Requirement already satisfied: psycopg2-binary in /usr/lib/python3.6/site-packages (from django-tenant-schemas)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from django-tenant-schemas)
Requirement already satisfied: Django>=1.11 in /usr/local/lib/python3.6/dist-packages (from django-tenant-schemas)
Requirement already satisfied: asgiref~=3.2 in /usr/local/lib/python3.6/dist-packages (from Django>=1.11->django-tenant-schemas)**
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.6/dist-packages (from Django>=1.11->django-tenant-schemas)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from Django>=1.11->django-tenant-schemas)
(venv) root@vps21715:/meuapp/portalcliente#

**Comment by VidyaYadavv1519** [comment]
Install tenant-schemas by using

pip install django-tenant-schemas
