### ISSUE TITLE
error 500 DEBUG=False  in production

### ISSUE THREAD

**Issue by alejandrohdo** [bernardopires/django-tenant-schemas#692]
Hello, I have my application that works fine in development mode and in production only with the DEBUG=True option, when I try to set this to False in production, it always gives me a 500 error for all my custom templates; however normally I can access the django admin panel(/admin). Everything tells me that the STATIC something is wrong. For example, in the case of MEDIA, I see that it is created correctly in each tenant. Has anyone experienced this problem? Thanks a lot

Error:
```
Error 500
Server Error
There's been an error. It's been reported to the site administrators via e-mail and should be fixed shortly. Thanks for your patience.
```

**Comment by alejandrohdo** [comment]
Apparently it is some problem of this type https://github.com/django-tenants/django-tenants/issues/544

I just did it, and it throws me an error
python manage.py collectstatic_schemas --noinput
```
== Switching to schema 'public' then calling collectstatic:
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/tenant_schemas/management/commands/__init__.py", line 95, in handle
    self.execute_command(tenant, self.COMMAND_NAME, *args, **options)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/tenant_schemas/management/commands/__init__.py", line 74, in execute_command
    call_command(command_name, *args, **options)
  File "/home/rimay/env_rimayapp/lib/python3.8/site-packages/django/core/management/__init__.py", line 135, in call_command
    raise TypeError(
TypeError: Unknown option(s) for collectstatic command: schema_name, skip_public. Valid options are: clear, dry_run, force_color, help, ignore, ignore_patterns, interactive, link, no_color, no_default_ignore, no_input, no_post_process, post_process, pythonpath, settings, skip_checks, stderr, stdout, traceback, use_default_ignore_patterns, verbosity, version.

```

**Comment by goodtune** [comment]
There is insufficient detail here to try and resolve this.

I've marked as `bug` but I am closing it as `wontfix` because without a stack trace it is impossible to know if this is framework or a project error.
